name: Update Date

on:
  push:
    branches:
      - main

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check repository status and Update
        run: |
          git fetch
          status=$(git status -uno -s)
          if [[ -n $status ]]; then
            current_date=$(date +%B' '%d', '%Y)
            sed -i "s/{{DATE}}/$current_date/" README.md
          else
            echo "Repository is up to date. Skipping action."
            exit 0
          fi
      
      

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update date [skip ci]"
          git push
